### ISSUE TITLE
Query regarding v16 compatibility 

### ISSUE THREAD

**Issue by wmssoft-au** [gmarczynski/odoo-web-progress#25]
Hello Grzegorz,

Are you creating a version that is Odoo v16 compatible and if so, when?

Regards

John

**Comment by gmarczynski** [comment]
Hello John,

I am working on it, but the delivery time is unknown. It may take a little while, because I need to plug into the new OWL-based web client communication pattern.

First I will handle the Odoo v15 compatibility and then the v16 which should be straightforward, because the major change was already included in the former.

I wil keep you posted.

Best,
Grzegorz

**Comment by pafnow** [comment]
Hi Grzegorz,
Thanks for your module.
I've moved to v16 and its one of those I miss the most.
I've seen you ported to v15 already so I tried to see how I could adapt to v16 but it seems to not be that easy.
Have you made any progress on your side ?
regards

**Comment by gmarczynski** [comment]
Hello,

The v16 is out. Briefly tested only, so please report any issues.

Enjoy!

Best,
Grzegorz

**Comment by pafnow** [comment]
Hi,
I've tested it today and so far so good.
Thanks a lot !
